Change default user (3)

diff --git a/debian/trafficserver.postinst b/debian/trafficserver.postinst
--- a/debian/trafficserver.postinst
+++ b/debian/trafficserver.postinst
@@ -1,18 +1,64 @@
 #! /usr/bin/env sh
+# postinst script for trafficserver
+#
+# see: dh_installdeb(1)
+
+set -e
 
 USER='trafficserver'
 USER_HOME='/var/run/trafficserver'
 
-if ! getent passwd $USER >/dev/null 2>&1 ; then
-    adduser --home $USER_HOME \
-       --system \
-       --disabled-password \
-       --gecos "Debian Traffic Server user" \
-	$USER
-fi
+# summary of how this script can be called:
+#        * <postinst> `configure' <most-recently-configured-version>
+#        * <old-postinst> `abort-upgrade' <new version>
+#        * <conflictor's-postinst> `abort-remove' `in-favour' <package>
+#          <new-version>
+#        * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
+#          <failed-install-package> <version> `removing'
+#          <conflicting-package> <version>
+# for details, see /usr/share/doc/packaging-manual/
+#
+# quoting from the policy:
+#     Any necessary prompting should almost always be confined to the
+#     post-installation script, and should be protected with a conditional
+#     so that unnecessary prompting doesn't happen if a package's
+#     installation fails and the `postinst' is called with `abort-upgrade',
+#     `abort-remove' or `abort-deconfigure'.
 
-install -d -m 0755 -o $USER -g nogroup /var/log/trafficserver
-chmod 0755 /etc/trafficserver /var/run/trafficserver
-chown -R $USER:nogroup /etc/trafficserver
-chown $USER:nogroup /var/run/trafficserver
+case "$1" in
+configure)
+
+	if ! getent passwd $USER >/dev/null 2>&1 ; then
+	    adduser --home $USER_HOME \
+	       --system \
+	       --disabled-password \
+	       --gecos "Debian Traffic Server user" \
+		$USER
+	fi
+
+	install -d -m 0755 -o $USER -g nogroup /var/log/trafficserver
+	chmod 0755 /etc/trafficserver /var/run/trafficserver
+	chown -R $USER:nogroup /etc/trafficserver
+	chown $USER:nogroup /var/run/trafficserver
+
+;;
+
+abort-upgrade|abort-remove|abort-deconfigure)
+
+;;
+
+*)
+echo "postinst called with unknown argument \`$1'" >&2
+exit 0
+;;
+esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
+
+#DEBHELPER#
+
+exit 0
+
+
 
